DROP TABLE IF EXISTS EMPLOYEE;
CREATE TABLE EMPLOYEE (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  email VARCHAR(100) DEFAULT NULL
);

DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  user_name VARCHAR(250) NOT NULL,
  password VARCHAR(250) NOT NULL,
  active VARCHAR(10) DEFAULT NULL,
  role_id INT NOT NULL
);

DROP TABLE IF EXISTS ROLE;
CREATE TABLE ROLE (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  role_id INT NOT NULL,
  name VARCHAR(100) NOT NULL
);